-- =====================================================================
-- ESQUEMA DE BASE DE DATOS: RÚBRICAS Y SUBNOTAS (DIVISIST ↔ MOODLE)
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. VERSIÓN PARA ORACLE (Esquema Institucional / database2)
-- ---------------------------------------------------------------------

-- Tabla para almacenar la configuración de la rúbrica definida por el docente
CREATE TABLE CONFIG_RUBRICA (
    ID                  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    COD_PROFESOR        VARCHAR2(20) NOT NULL,
    COD_MATERIA         VARCHAR2(20) NOT NULL,
    GRUPO               VARCHAR2(5)  NOT NULL,
    SEMESTRE            VARCHAR2(10) NOT NULL,
    TIPO_PREVIO         VARCHAR2(20) NOT NULL, -- '1', '2', '3', 'FINAL'
    ID_ACTIVIDAD_MOODLE NUMBER NOT NULL,       -- ID del módulo/actividad en Moodle
    NOMBRE_ACTIVIDAD    VARCHAR2(200) NOT NULL,
    TIPO_ACTIVIDAD      VARCHAR2(50),          -- 'quiz', 'assign', 'forum', etc.
    PORCENTAJE          NUMBER(5,2) NOT NULL,  -- Ej. 30.00 para 30%
    FECHA_CREACION      DATE DEFAULT SYSDATE
);

-- Índices para optimizar búsquedas por curso y corte
CREATE INDEX IDX_RUBRICA_BUSQUEDA ON CONFIG_RUBRICA (COD_PROFESOR, COD_MATERIA, GRUPO, SEMESTRE, TIPO_PREVIO);

-- Tabla para almacenar las subnotas y notas calculadas por estudiante
CREATE TABLE SUBNOTAS (
    ID                  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    COD_PROFESOR        VARCHAR2(20) NOT NULL,
    COD_MATERIA         VARCHAR2(20) NOT NULL,
    GRUPO               VARCHAR2(5)  NOT NULL,
    SEMESTRE            VARCHAR2(10) NOT NULL,
    COD_ESTUDIANTE      VARCHAR2(20) NOT NULL,
    TIPO_PREVIO         VARCHAR2(20) NOT NULL, -- '1', '2', '3'
    ID_ACTIVIDAD_MOODLE NUMBER NOT NULL,
    NOMBRE_ACTIVIDAD    VARCHAR2(200) NOT NULL,
    NOTA_ORIGINAL       NUMBER(5,2) DEFAULT 0, -- Calificación obtenida en Moodle
    NOTA_MAXIMA         NUMBER(5,2) DEFAULT 5, -- Escala máxima (5.0 o 100)
    PORCENTAJE          NUMBER(5,2) NOT NULL,  -- Porcentaje que valía en la rúbrica
    SUBNOTA             NUMBER(5,2) NOT NULL,  -- Puntos que aporta a la nota final
    ESTADO              VARCHAR2(20) DEFAULT 'SUGERIDA', -- 'SUGERIDA', 'ACEPTADA', 'MODIFICADA'
    FECHA_REGISTRO      DATE DEFAULT SYSDATE
);

CREATE INDEX IDX_SUBNOTAS_ESTUDIANTE ON SUBNOTAS (COD_ESTUDIANTE, COD_MATERIA, GRUPO, SEMESTRE, TIPO_PREVIO);
CREATE INDEX IDX_SUBNOTAS_GRUPO ON SUBNOTAS (COD_PROFESOR, COD_MATERIA, GRUPO, SEMESTRE, TIPO_PREVIO);


-- ---------------------------------------------------------------------
-- 2. VERSIÓN PARA MYSQL / MARIADB (Por si se despliega en local)
-- ---------------------------------------------------------------------
/*
CREATE TABLE IF NOT EXISTS config_rubrica (
    id INT AUTO_INCREMENT PRIMARY KEY,
    cod_profesor VARCHAR(20) NOT NULL,
    cod_materia VARCHAR(20) NOT NULL,
    grupo VARCHAR(5) NOT NULL,
    semestre VARCHAR(10) NOT NULL,
    tipo_previo VARCHAR(20) NOT NULL,
    id_actividad_moodle INT NOT NULL,
    nombre_actividad VARCHAR(200) NOT NULL,
    tipo_actividad VARCHAR(50),
    porcentaje DECIMAL(5,2) NOT NULL,
    fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_rubrica (cod_profesor, cod_materia, grupo, semestre, tipo_previo)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS subnotas (
    id INT AUTO_INCREMENT PRIMARY KEY,
    cod_profesor VARCHAR(20) NOT NULL,
    cod_materia VARCHAR(20) NOT NULL,
    grupo VARCHAR(5) NOT NULL,
    semestre VARCHAR(10) NOT NULL,
    cod_estudiante VARCHAR(20) NOT NULL,
    tipo_previo VARCHAR(20) NOT NULL,
    id_actividad_moodle INT NOT NULL,
    nombre_actividad VARCHAR(200) NOT NULL,
    nota_original DECIMAL(5,2) DEFAULT 0,
    nota_maxima DECIMAL(5,2) DEFAULT 5,
    porcentaje DECIMAL(5,2) NOT NULL,
    subnota DECIMAL(5,2) NOT NULL,
    estado VARCHAR(20) DEFAULT 'SUGERIDA',
    fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_subnotas_est (cod_estudiante, cod_materia, grupo, semestre, tipo_previo),
    INDEX idx_subnotas_grp (cod_profesor, cod_materia, grupo, semestre, tipo_previo)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
*/
